apiVersion: v1
kind: Service
metadata:
  name: nodejs-postgres-db
  labels:
    app: nodejs-postgres-db
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: nodejs-postgres-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-postgres-db-pv
  labels:
    app: nodejs-postgres-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-postgres-db
  labels:
    app: nodejs-postgres-db
spec:
  selector:
    matchLabels:
      app: nodejs-postgres-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodejs-postgres-db
    spec:
      containers:
        - image: postgres:14
          name: nodejs-postgres-db
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: senha
            - name: POSTGRES_DB
              value: demo
          resources:
            limits:
              cpu: "1000m"
              memory: "1.5Gi"
            requests:
              cpu: "1000m"
              memory: "1.5Gi"
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: nodejs-postgres-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: nodejs-postgres-volume
          persistentVolumeClaim:
            claimName: nodejs-postgres-db-pv
