apiVersion: v1
kind: Secret
metadata:
  name: nodejs-secrets
stringData:
  DATABASE_URL: "postgresql://postgres:senha@nodejs-postgres-db.default:5432/demo?connection_limit=9&pool_timeout=0"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "senha"
  POSTGRES_DB: "demo"
