apiVersion: v1
kind: Secret
metadata:
  name: nodejs-server-sa-token
  namespace: nodejs-server-dev
  annotations:
    kubernetes.io/service-account.name: nodejs-server-sa
type: kubernetes.io/service-account-token
